server:
  port: 8123
  servlet:
    context-path: /api
    # cookie30天过期
    session:
      cookie:
        max-age: 2592000

spring:
  profiles:
    active: local
  application:
    name: yu-pic_back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_pic
    username: root
    password:
  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  # session配置
  session:
    store-type: redis
    # 30天后过期
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
  # RabbitMq
  rabbitmq:
    host:
    port: 5672
    username: admin
    password:
  # 空间图片分表
  shardingsphere:
    datasource:
      names: yu_pic
      yu_pic:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yu_pic
        username: root
        password:
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yu_pic.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.whisky.yupicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境打印sql语句日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
#        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.whisky.yupicturebackend.controller



